name: Add custom domain

on: workflow_dispatch

jobs:
  add-domain:
    env:
      DOMAIN: 'fretofficial.com'
      CONFIG_SCRIPT: ${{ vars.CONFIG_SCRIPT }}
      RSA_KIRAN: ${{ secrets.SSH_PRIVATE_KEY }}
    if: github.ref_name  == 'gh-pages'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup configs for github access
        run: |
          echo $CONFIG_SCRIPT > github_actions.sh
          chmod +x github_actions.sh
          
      - name: Create CNAME file
        run: echo $DOMAIN > CNAME

      - name: Commit changes
        run: |
          echo [*] Running config CONFIG_SCRIPT...
          sh github_actions.sh
          git config --global user.email "kiranbanmala3@gmail.com"
          git config --global user.name "Github CI"
          git status
          git add CNAME
          git commit -m"Added CNAME file"
          git push origin gh-pages
