name: Update domain

on: workflow_dispatch 

jobs:
  add-domain:
    runs-on: ubuntu-latest
    env:
      RSA_KIRAN: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy files to home path
        run: |
          cp github_actions.sh ~/github_actions.sh
          cp CNAME ~/CNAME

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: gh-pages

      - name: Copy files to repository
        run: |
          cp ~/github_actions.sh ./github_actions.sh
          cp ~/CNAME ./CNAME
          sh github_actions.sh

      - name: Commit changes
        run: | 
          gti pull
          git status
          git add CNAME
          git commit -m"Added CNAME file"
          git push origin gh-pages
